---
title: "Phylogenetic Tree BBS Project"
author: "Ina Koehler"
date: "2024-01-21"
output: html_document
---

```{r, include = FALSE, message = FALSE}
## Install packages if not already installed
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ggtree")
install.packages("ape")

```

1. Load libraries and set working directory:

```{r, setup, include = FALSE}
## Load libraries and set global working directory
library(ggplot2)
library(ggtree)
library(ape)

knitr::opts_knit$set(root.dir = '/home/inak/bbs_project/data/phylogenetic_tree/')
```

2. Load input data

```{r, include = FALSE}
# Assuming your Newick tree is stored in a file named "tree.newick"
species_data <- read.tree("SpeciesTree_rooted_node_labels.txt")
bbs1_data <- read.tree("BBS1_tree.txt")
bbs2_data <- read.tree("BBS2_tree.txt")
bbs4_data <- read.tree("BBS4_tree.txt")
bbs5_data <- read.tree("BBS5_tree.txt")
bbs7_data <- read.tree("BBS7_tree.txt")
bbs8_data <- read.tree("BBS8_tree.txt")
bbs9_data <- read.tree("BBS9_tree.txt")
bbs12_data <- read.tree("BBS12_tree.txt")

tree_plot <- function(data, title) {
  ggtree(data, layout="slanted") +
  geom_tiplab() +
  theme_tree2() +
  xlim(0,2.5) +
  ggtitle(title)
}

```

```{r, include = FALSE}
# Create the plot
species_tree <- tree_plot(species_data, "Species tree")

bbs1_tree <- tree_plot(bbs1_data, "BBS1")
bbs2_tree <- tree_plot(bbs2_data, "BBS2") 
bbs4_tree <- tree_plot(bbs4_data, "BBS4")
bbs5_tree <- tree_plot(bbs5_data, "BBS5")
bbs7_tree <- tree_plot(bbs7_data, "BBS7")
bbs8_tree <- tree_plot(bbs8_data, "BBS8")
bbs8_tree <- flip(bbs8_tree, 17, 21)
bbs9_tree <- tree_plot(bbs9_data, "BBS9")

```


```{r}
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/species_tree.pdf",
       plot = species_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs1_tree.pdf",
       plot = bbs1_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs2_tree.pdf",
       plot = bbs2_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs4_tree.pdf",
       plot = bbs4_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs5_tree.pdf",
       plot = bbs5_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs7_tree.pdf",
       plot = bbs7_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs8_tree.pdf",
       plot = bbs8_tree,
       height = 3,
       width = 9)
ggsave(filename = "/home/inak/bbs_project/results/phylogenetic_tree/bbs9_tree.pdf",
       plot = bbs9_tree,
       height = 3,
       width = 9)

```

